spring.application.name=Agriconnect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework

app.frontend-url=${FRONTEND_URL}
admin.email=${ADMIN_EMAIL}
admin.phonenumber=${ADMIN_PHONENUMBER}
admin.password=${ADMIN_PASSWORD}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

africastalking.username=${AT_USERNAME:sandbox}
africastalking.api-key=${AT_API_KEY:}
africastalking.sender-id=${AT_SENDER_ID:}
africastalking.base-url=${AT_BASE_URL:https://api.sandbox.africastalking.com}


server.port=${PORT:8085}